### ISSUE TITLE
Error while trying to play songs

### ISSUE THREAD

**Issue by 3underscoreN** [3underscoreN/3_n-s-slash-Music-Bot#5]
Upon playing, the bot shows the following message:
ApplicationCommandInvokeError("Application Command raised an exception: TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'")
Play using links, keywords & internal search have all been tried. None of these works.

**Comment by 3underscoreN** [comment]
I was able to recreate this in another environment:
```
>>> item = pafy.new('https://www.youtube.com/watch?v=g3jCAyPai2Y')
>>> item.getbestaudio()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cychandt/.local/lib/python3.10/site-packages/pafy/backend_shared.py", line 405, in getbestaudio
    if not self.audiostreams:
  File "/Users/cychandt/.local/lib/python3.10/site-packages/pafy/backend_shared.py", line 176, in audiostreams
    self._process_streams()
  File "/Users/cychandt/.local/lib/python3.10/site-packages/pafy/backend_youtube_dl.py", line 82, in _process_streams
    allstreams = [YtdlStream(z, self) for z in self._ydl_info['formats']]
  File "/Users/cychandt/.local/lib/python3.10/site-packages/pafy/backend_youtube_dl.py", line 82, in <listcomp>
    allstreams = [YtdlStream(z, self) for z in self._ydl_info['formats']]
  File "/Users/cychandt/.local/lib/python3.10/site-packages/pafy/backend_youtube_dl.py", line 106, in __init__
    self._rawbitrate = info.get('abr', 0) * 1024
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

**Comment by 3underscoreN** [comment]
Looks like the problem is in pafy with this undefined behaviour:
```python
class YtdlStream(BaseStream):
  ......
        self._rawbitrate = info.get('abr', 0) * 1024
```
after further investigation, it looks like that newest version of yt_dlp might have 'abr' attribute set to `None`, which would cause the issue `TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'`.

For the purpose of this bot, we can modify the line into:
```python
        if temp_abr := info.get('abr', 0):
            self._rawbitrate = temp_abr * 1024
        else:
            self._rawbitrate = 0
```
